version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: trocaumaideia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=trocaumaideia.settings

volumes:
  postgres_data:
