name: Django Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: trocaumaideia
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: fake-key
      DEBUG: 1
      DB_NAME: trocaumaideia
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências com Poetry
        working-directory: backend
        run: poetry install

      - name: Verificar formatação com Black
        working-directory: backend
        run: poetry run black . --check

      - name: Verificar ordenação com isort
        working-directory: backend
        run: poetry run isort . --check-only

      - name: Rodar testes
        working-directory: backend
        run: poetry run python manage.py test
