# Generated by Django 4.2.21 on 2025-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talkzone", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
