# Generated by Django 4.2.21 on 2025-06-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("talkzone", "0005_profile_followers_tweet_is_retweet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="is_retweet",
            new_name="is_repapo",
        ),
        migrations.AddField(
            model_name="tweet",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="talkzone.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
